name: Run tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        case: ["bomex", "benchmark/rico"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install build dependencies
        run: |
          sudo sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
          sudo apt-get update
          sudo apt-get install -y cmake libfftw3-dev libhypre-dev libnetcdf-dev libopenmpi-dev libnetcdff-dev

      - name: Set up Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=DEBUG -DUSE_FFTW=True ..

      - name: Build
        run: |
          cd build
          make -j 2

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Run tests
        run: |
          export DALES=$(find ~+/build/src -maxdepth 1 -name "dales*")
          pytest -rf --assert=plain --case=${{ matrix.case }}
          
